const CONSTANTS = {
  //Type Image
  "workingLogo": "assets/images/illustration-working.svg",
  "twitterLogo": "assets/images/icon-twitter.svg",
  "instagramLogo": "assets/images/icon-instagram.svg",
  "facebookLogo": "assets/images/icon-facebook.svg",
  "shortlyLogo": "assets/images/logo.svg",
  "pinterestLogo": "assets/images/icon-pinterest.svg",
  "fullyCustomLogo": "assets/images/icon-fully-customizable.svg",
  "recordDetailLogo": "assets/images/icon-detailed-records.svg",
  "recognitionLogo": "assets/images/icon-brand-recognition.svg",
  "hamburgerLogo": "assets/images/icon-hamburger.svg",
  "closeLogo": "assets/images/icon-close.svg",
  "whiteLogo": "assets/images/logo-white.svg",

  //Type Text
  "featuresText": "Features",
  "pricingText": "Pricing",
  "resourcesText": "Resources",
  "linkShorteningText": "Link Shortening",
  "brandedLinksText": "Branded Links",
  "analyticsText": "Analytics",
  "blogText": "Blog",
  "developersText": "Developers",
  "supportText": "Support",
  "companyText": "Company",
  "aboutText": "About",
  "ourTeamText": "Our Team",
  "careersText": "Careers",
  "contactText": "Contact",
  "shortenText": "Shorten it!",
  "loginText": "Login",
  "signUpText": "Sign Up",
  "yourLinksText": "Your links",
  "pleaseAddText": "Please add a link",
  "contentTitleText": "More than just shorter links",
  "contentText": "Build your brand’s recognition and get detailed insights on how your links are performing.",
  "advancedText": "Advanced statistics",
  "contentAdvancedText": "Track how your links are performing across the web with our detailed statistics dashboard.",
  "detailRecordText": "Detailed records",
  "contentRecordText": "Gain insights into who is clicking your links. Knowing when and where people engage with your content helps inform better decisions.",
  "recognitionText": "Brand recognition",
  "detailRecognitionText": "Boost your brand recognition with each click. Generic links don't mean a thing. Branded links help instill confidence in your product.",
  "customizableText": "Fully customizable",
  "contentCustomizableText": "Improve brand awareness and content discoverability through customizable links, supercharging audience engagement.",

}

export default CONSTANTS;
